name: Daily LeetCode Sync

on:
  # Allows you to trigger the workflow manually from the Actions tab
  workflow_dispatch:
  # Sets the workflow to run automatically every day
  schedule:
    # CRON Expression: 'minute hour day_of_month month day_of_week'
    # '0 12 * * *' = Runs at 12:00 PM UTC every day.
    # IMPORTANT: GitHub Actions use UTC time zone. Adjust the 'hour' (12) to match your desired local time.
    - cron: '0 12 * * *' 

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v4
        
      # 2. Run the LeetCode Sync Action
      - name: Sync LeetCode Submissions
        uses: joshcai/leetcode-sync@v1.7
        with:
          # Uses the built-in GitHub token for pushing commits
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          # Uses the secrets you created in Step 3
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          # Optional: Skip new submissions for the same problem within a day (86400 seconds)
          filter-duplicate-secs: 86400
